export type MuiOverrideTarget = {
  muiKey: string
  label: string
  classKeys: string[]
}

export type ComponentCustomizeCatalogEntry = {
  sampleId: string
  title: string
  targets: MuiOverrideTarget[]
}

const switchBaseClassKeys = ["root", "checked", "disabled", "input"]

const inputBaseClassKeys = [
  "root",
  "formControl",
  "focused",
  "disabled",
  "adornedEnd",
  "adornedStart",
  "error",
  "marginDense",
  "multiline",
  "fullWidth",
  "colorSecondary",
  "input",
  "inputMarginDense",
  "inputMultiline",
  "inputTypeSearch",
  "inputAdornedStart",
  "inputAdornedEnd",
  "inputHiddenLabel",
]

export const muiClassKeys: Record<string, string[]> = {
  MuiAccordion: ["root", "rounded", "expanded", "disabled"],
  MuiAccordionActions: ["root", "spacing"],
  MuiAccordionDetails: ["root"],
  MuiAccordionSummary: [
    "root",
    "expanded",
    "focused",
    "disabled",
    "content",
    "expandIcon",
  ],
  MuiAppBar: [
    "root",
    "positionFixed",
    "positionAbsolute",
    "positionSticky",
    "positionStatic",
    "positionRelative",
    "colorDefault",
    "colorPrimary",
    "colorSecondary",
    "colorInherit",
    "colorTransparent",
  ],
  MuiToolbar: ["root", "gutters", "regular", "dense"],
  MuiAvatar: [
    "root",
    "colorDefault",
    "circle",
    "rounded",
    "square",
    "img",
    "fallback",
  ],
  MuiBadge: [
    "root",
    "badge",
    "colorPrimary",
    "colorSecondary",
    "colorError",
    "dot",
    "anchorOriginTopRightRectangle",
    "anchorOriginBottomRightRectangle",
    "anchorOriginTopLeftRectangle",
    "anchorOriginBottomLeftRectangle",
    "anchorOriginTopRightCircle",
    "anchorOriginBottomRightCircle",
    "anchorOriginTopLeftCircle",
    "invisible",
  ],
  MuiBottomNavigation: ["root"],
  MuiBottomNavigationAction: [
    "root",
    "selected",
    "iconOnly",
    "wrapper",
    "label",
  ],
  MuiButton: [
    "root",
    "label",
    "text",
    "textPrimary",
    "textSecondary",
    "outlined",
    "outlinedPrimary",
    "outlinedSecondary",
    "contained",
    "containedPrimary",
    "containedSecondary",
    "disableElevation",
    "focusVisible",
    "disabled",
    "colorInherit",
    "textSizeSmall",
    "textSizeLarge",
    "outlinedSizeSmall",
    "outlinedSizeLarge",
    "containedSizeSmall",
    "containedSizeLarge",
    "sizeSmall",
    "sizeLarge",
    "fullWidth",
    "startIcon",
    "endIcon",
    "iconSizeSmall",
    "iconSizeMedium",
    "iconSizeLarge",
  ],
  MuiCard: ["root"],
  MuiCardActionArea: ["root", "focusVisible", "focusHighlight"],
  MuiCardActions: ["root", "spacing"],
  MuiCardContent: ["root"],
  MuiCardHeader: ["root", "avatar", "action", "content", "title", "subheader"],
  MuiCardMedia: ["root", "media"],
  MuiCheckbox: [
    ...switchBaseClassKeys,
    "indeterminate",
    "colorPrimary",
    "colorSecondary",
  ],
  MuiChip: [
    "root",
    "sizeSmall",
    "colorPrimary",
    "colorSecondary",
    "disabled",
    "clickable",
    "clickableColorPrimary",
    "clickableColorSecondary",
    "deletable",
    "deletableColorPrimary",
    "deletableColorSecondary",
    "outlined",
    "outlinedPrimary",
    "outlinedSecondary",
    "avatar",
    "avatarSmall",
    "avatarColorPrimary",
    "avatarColorSecondary",
    "icon",
    "iconSmall",
    "iconColorPrimary",
    "iconColorSecondary",
    "label",
    "labelSmall",
    "deleteIcon",
    "deleteIconSmall",
    "deleteIconColorPrimary",
    "deleteIconColorSecondary",
    "deleteIconOutlinedColorPrimary",
    "deleteIconOutlinedColorSecondary",
  ],
  MuiDialog: [
    "root",
    "scrollPaper",
    "scrollBody",
    "container",
    "paper",
    "paperScrollPaper",
    "paperScrollBody",
    "paperWidthFalse",
    "paperWidthXs",
    "paperWidthSm",
    "paperWidthMd",
    "paperWidthLg",
    "paperWidthXl",
    "paperFullWidth",
    "paperFullScreen",
  ],
  MuiDialogActions: ["root", "spacing"],
  MuiDialogContent: ["root", "dividers"],
  MuiDialogContentText: ["root"],
  MuiDialogTitle: ["root"],
  MuiFab: [
    "root",
    "label",
    "primary",
    "secondary",
    "extended",
    "focusVisible",
    "disabled",
    "colorInherit",
    "sizeSmall",
    "sizeMedium",
  ],
  MuiIcon: [
    "root",
    "colorSecondary",
    "colorAction",
    "colorDisabled",
    "colorError",
    "colorPrimary",
    "fontSizeInherit",
    "fontSizeSmall",
    "fontSizeLarge",
  ],
  MuiSvgIcon: [
    "root",
    "colorSecondary",
    "colorAction",
    "colorDisabled",
    "colorError",
    "colorPrimary",
    "fontSizeInherit",
    "fontSizeSmall",
    "fontSizeLarge",
  ],
  MuiList: ["root", "padding", "dense", "subheader"],
  MuiListItem: [
    "root",
    "container",
    "focusVisible",
    "default",
    "dense",
    "disabled",
    "divider",
    "gutters",
    "button",
    "secondaryAction",
    "selected",
  ],
  MuiListItemText: [
    "root",
    "multiline",
    "dense",
    "inset",
    "primary",
    "secondary",
  ],
  MuiListItemIcon: ["root", "alignItemsFlexStart"],
  MuiListItemAvatar: ["root", "icon"],
  MuiListItemSecondaryAction: ["root"],
  MuiListSubheader: [
    "root",
    "colorPrimary",
    "colorInherit",
    "inset",
    "sticky",
    "gutters",
  ],
  MuiMenu: ["paper", "list"],
  MuiMenuItem: ["root", "gutters", "selected", "dense"],
  MuiCircularProgress: [
    "root",
    "static",
    "indeterminate",
    "colorPrimary",
    "colorSecondary",
    "svg",
    "circle",
    "circleStatic",
    "circleIndeterminate",
    "circleDisableShrink",
  ],
  MuiLinearProgress: [
    "root",
    "colorPrimary",
    "colorSecondary",
    "determinate",
    "indeterminate",
    "buffer",
    "query",
    "dashed",
    "dashedColorPrimary",
    "dashedColorSecondary",
    "bar",
    "barColorPrimary",
    "barColorSecondary",
    "bar1Indeterminate",
    "bar2Indeterminate",
    "bar1Determinate",
    "bar1Buffer",
    "bar2Buffer",
  ],
  MuiRadio: [...switchBaseClassKeys, "colorPrimary", "colorSecondary"],
  MuiSelect: [
    "root",
    "select",
    "filled",
    "outlined",
    "selectMenu",
    "disabled",
    "icon",
    "iconOpen",
    "iconFilled",
    "iconOutlined",
  ],
  MuiInput: [
    "root",
    "formControl",
    "focused",
    "disabled",
    "colorSecondary",
    "underline",
    "error",
    "marginDense",
    "multiline",
    "fullWidth",
    "input",
    "inputMarginDense",
    "inputMultiline",
    "inputTypeSearch",
  ],
  MuiOutlinedInput: [
    "root",
    "colorSecondary",
    "focused",
    "disabled",
    "adornedStart",
    "adornedEnd",
    "error",
    "marginDense",
    "multiline",
    "notchedOutline",
    "input",
    "inputMarginDense",
    "inputMultiline",
    "inputAdornedStart",
    "inputAdornedEnd",
  ],
  MuiFilledInput: [...inputBaseClassKeys, "underline"],
  MuiSlider: [
    "root",
    "colorPrimary",
    "colorSecondary",
    "marked",
    "vertical",
    "disabled",
    "rail",
    "track",
    "trackFalse",
    "trackInverted",
    "thumb",
    "thumbColorPrimary",
    "thumbColorSecondary",
    "active",
    "focusVisible",
    "valueLabel",
    "mark",
    "markActive",
    "markLabel",
    "markLabelActive",
  ],
  MuiSnackbar: [
    "root",
    "anchorOriginTopCenter",
    "anchorOriginBottomCenter",
    "anchorOriginTopRight",
    "anchorOriginBottomRight",
    "anchorOriginTopLeft",
    "anchorOriginBottomLeft",
  ],
  MuiSnackbarContent: ["root", "message", "action"],
  MuiStepper: ["root", "horizontal", "vertical", "alternativeLabel"],
  MuiStep: ["root", "horizontal", "vertical", "alternativeLabel", "completed"],
  MuiStepLabel: [
    "root",
    "horizontal",
    "vertical",
    "active",
    "completed",
    "alternativeLabel",
    "error",
    "disabled",
    "label",
    "iconContainer",
    "labelContainer",
  ],
  MuiStepContent: ["root", "last", "transition"],
  MuiStepConnector: [
    "root",
    "horizontal",
    "vertical",
    "alternativeLabel",
    "active",
    "completed",
    "disabled",
    "line",
    "lineHorizontal",
    "lineVertical",
  ],
  MuiStepIcon: ["root", "text", "active", "completed", "error"],
  MuiSwitch: [
    ...switchBaseClassKeys,
    "switchBase",
    "colorPrimary",
    "colorSecondary",
    "sizeSmall",
    "thumb",
    "track",
  ],
  MuiTable: ["root", "stickyHeader"],
  MuiTableContainer: ["root"],
  MuiTableRow: ["root", "selected", "hover", "head", "footer"],
  MuiTableCell: [
    "root",
    "head",
    "body",
    "footer",
    "alignLeft",
    "alignCenter",
    "alignRight",
    "alignJustify",
    "sizeSmall",
    "paddingCheckbox",
    "paddingNone",
    "stickyHeader",
  ],
  MuiTableHead: ["root"],
  MuiTableBody: ["root"],
  MuiTableFooter: ["root"],
  MuiTablePagination: [
    "root",
    "toolbar",
    "spacer",
    "menuItem",
    "caption",
    "input",
    "selectRoot",
    "select",
    "selectIcon",
    "actions",
  ],
  MuiTableSortLabel: [
    "root",
    "active",
    "icon",
    "iconDirectionDesc",
    "iconDirectionAsc",
  ],
  MuiTabs: [
    "root",
    "flexContainer",
    "scroller",
    "fixed",
    "scrollable",
    "centered",
    "scrollButtons",
    "scrollButtonsDesktop",
    "indicator",
  ],
  MuiTab: [
    "root",
    "labelIcon",
    "textColorInherit",
    "textColorPrimary",
    "textColorSecondary",
    "selected",
    "disabled",
    "fullWidth",
    "wrapped",
    "wrapper",
  ],
  MuiTextField: ["root"],
  MuiFormControl: ["root", "marginNormal", "marginDense", "fullWidth"],
  MuiInputLabel: [
    "root",
    "focused",
    "disabled",
    "error",
    "required",
    "asterisk",
    "formControl",
    "marginDense",
    "shrink",
    "animated",
    "filled",
    "outlined",
  ],
  MuiInputBase: inputBaseClassKeys,
  MuiFormHelperText: [
    "root",
    "error",
    "disabled",
    "marginDense",
    "focused",
    "filled",
    "contained",
    "required",
  ],
  MuiTooltip: [
    "popper",
    "popperInteractive",
    "popperArrow",
    "tooltip",
    "tooltipArrow",
    "arrow",
    "touch",
    "tooltipPlacementLeft",
    "tooltipPlacementRight",
    "tooltipPlacementTop",
    "tooltipPlacementBottom",
  ],
  MuiTypography: [
    "root",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "subtitle1",
    "subtitle2",
    "body1",
    "body2",
    "caption",
    "button",
    "overline",
    "srOnly",
    "alignLeft",
    "alignCenter",
    "alignRight",
    "alignJustify",
    "noWrap",
    "gutterBottom",
    "paragraph",
    "colorInherit",
    "colorPrimary",
    "colorSecondary",
    "colorTextPrimary",
    "colorTextSecondary",
    "colorError",
    "displayInline",
    "displayBlock",
  ],
}

function target(muiKey: string): MuiOverrideTarget {
  return {
    muiKey,
    label: muiKey.replace(/^Mui/, ""),
    classKeys: muiClassKeys[muiKey],
  }
}

export const componentCustomizeCatalog: ComponentCustomizeCatalogEntry[] = [
  {
    sampleId: "Accordion",
    title: "Accordion",
    targets: [
      target("MuiAccordion"),
      target("MuiAccordionSummary"),
      target("MuiAccordionDetails"),
      target("MuiAccordionActions"),
    ],
  },
  {
    sampleId: "Appbar",
    title: "App Bar",
    targets: [target("MuiAppBar"), target("MuiToolbar")],
  },
  {
    sampleId: "Avatar",
    title: "Avatar",
    targets: [target("MuiAvatar")],
  },
  {
    sampleId: "Badge",
    title: "Badge",
    targets: [target("MuiBadge")],
  },
  {
    sampleId: "BottomNavigation",
    title: "Bottom Navigation",
    targets: [
      target("MuiBottomNavigation"),
      target("MuiBottomNavigationAction"),
    ],
  },
  {
    sampleId: "Buttons",
    title: "Buttons",
    targets: [target("MuiButton")],
  },
  {
    sampleId: "Card",
    title: "Card",
    targets: [
      target("MuiCard"),
      target("MuiCardHeader"),
      target("MuiCardContent"),
      target("MuiCardActions"),
      target("MuiCardMedia"),
      target("MuiCardActionArea"),
    ],
  },
  {
    sampleId: "Checkboxes",
    title: "Checkboxes",
    targets: [target("MuiCheckbox")],
  },
  {
    sampleId: "Chip",
    title: "Chip",
    targets: [target("MuiChip")],
  },
  {
    sampleId: "Dialog",
    title: "Dialog",
    targets: [
      target("MuiDialog"),
      target("MuiDialogTitle"),
      target("MuiDialogContent"),
      target("MuiDialogContentText"),
      target("MuiDialogActions"),
    ],
  },
  {
    sampleId: "FloatingActionButton",
    title: "Floating Action Button",
    targets: [target("MuiFab")],
  },
  {
    sampleId: "Icon",
    title: "Icon",
    targets: [target("MuiIcon"), target("MuiSvgIcon")],
  },
  {
    sampleId: "List",
    title: "List",
    targets: [
      target("MuiList"),
      target("MuiListItem"),
      target("MuiListItemText"),
      target("MuiListItemIcon"),
      target("MuiListItemAvatar"),
      target("MuiListItemSecondaryAction"),
      target("MuiListSubheader"),
    ],
  },
  {
    sampleId: "Menu",
    title: "Menu",
    targets: [target("MuiMenu"), target("MuiMenuItem")],
  },
  {
    sampleId: "Progress",
    title: "Progress",
    targets: [target("MuiCircularProgress"), target("MuiLinearProgress")],
  },
  {
    sampleId: "Radio",
    title: "Radio",
    targets: [target("MuiRadio")],
  },
  {
    sampleId: "Select",
    title: "Select",
    targets: [
      target("MuiSelect"),
      target("MuiInput"),
      target("MuiOutlinedInput"),
      target("MuiFilledInput"),
    ],
  },
  {
    sampleId: "Slider",
    title: "Slider",
    targets: [target("MuiSlider")],
  },
  {
    sampleId: "Snackbar",
    title: "Snackbar",
    targets: [target("MuiSnackbar"), target("MuiSnackbarContent")],
  },
  {
    sampleId: "Stepper",
    title: "Stepper",
    targets: [
      target("MuiStepper"),
      target("MuiStep"),
      target("MuiStepLabel"),
      target("MuiStepContent"),
      target("MuiStepConnector"),
      target("MuiStepIcon"),
    ],
  },
  {
    sampleId: "Switch",
    title: "Switch",
    targets: [target("MuiSwitch")],
  },
  {
    sampleId: "Table",
    title: "Table",
    targets: [
      target("MuiTable"),
      target("MuiTableContainer"),
      target("MuiTableRow"),
      target("MuiTableCell"),
      target("MuiTableHead"),
      target("MuiTableBody"),
      target("MuiTableFooter"),
      target("MuiTablePagination"),
      target("MuiTableSortLabel"),
    ],
  },
  {
    sampleId: "Tabs",
    title: "Tabs",
    targets: [target("MuiTabs"), target("MuiTab")],
  },
  {
    sampleId: "TextField",
    title: "TextField",
    targets: [
      target("MuiTextField"),
      target("MuiFormControl"),
      target("MuiInputLabel"),
      target("MuiInputBase"),
      target("MuiInput"),
      target("MuiFilledInput"),
      target("MuiOutlinedInput"),
      target("MuiFormHelperText"),
    ],
  },
  {
    sampleId: "Tooltip",
    title: "Tooltip",
    targets: [target("MuiTooltip")],
  },
  {
    sampleId: "Typography",
    title: "Typography",
    targets: [target("MuiTypography")],
  },
]

export function getComponentCustomizeEntry(
  sampleId: string
): ComponentCustomizeCatalogEntry | undefined {
  return componentCustomizeCatalog.find(entry => entry.sampleId === sampleId)
}

export function getComponentOverrideResetConfigs(
  targets: MuiOverrideTarget[]
): { path: string; value: null }[] {
  return targets.map(target => ({
    path: `overrides.${target.muiKey}`,
    value: null,
  }))
}
